package pl.download.graphic;

import javax.swing.JOptionPane;
import pl.download.model.Model;

/**
 *
 * @author Artur Kokott
 */
public class Graphic extends javax.swing.JFrame {

    /**
     * Creates new form NewGraphic
     */
    public Graphic() {
        super("Generator linków");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numberFile = new javax.swing.JTextField();
        genereteButton = new javax.swing.JButton();
        showFilesButton = new javax.swing.JButton();
        wgetRadio = new javax.swing.JRadioButton();
        numberFileLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        generateLinkField = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);

        genereteButton.setText("Generuj");
        genereteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genereteButtonActionPerformed(evt);
            }
        });

        showFilesButton.setText("Pokaz dostepne pliki");
        showFilesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showFilesButtonActionPerformed(evt);
            }
        });

        wgetRadio.setSelected(true);
        wgetRadio.setText("Generuj wget");

        numberFileLabel.setText("Podaj numer pliku");

        generateLinkField.setEditable(false);
        generateLinkField.setColumns(20);
        generateLinkField.setRows(5);
        jScrollPane1.setViewportView(generateLinkField);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(showFilesButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(numberFileLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(genereteButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(wgetRadio))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(numberFile, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(numberFileLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numberFile, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(genereteButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(wgetRadio))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(showFilesButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void genereteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genereteButtonActionPerformed
        Model model = new Model();
        String getNumberFile = numberFile.getText();
        generateLinkField.setLineWrap(true);
        int radioSelected;

        if (getNumberFile == null || getNumberFile.equals("")) {
            JOptionPane.showMessageDialog(null, "Pole nie może być puste", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (wgetRadio.isSelected()) {
                radioSelected = 1;
            } else {
                radioSelected = 0;
            }
            try {
                generateLinkField.setText(model.link(getNumberFile, radioSelected));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Musisz podać liczbę!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }


    }//GEN-LAST:event_genereteButtonActionPerformed

    private void showFilesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showFilesButtonActionPerformed
        ShowFiles sf = new ShowFiles();
        sf.setVisible(true);
    }//GEN-LAST:event_showFilesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Graphic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Graphic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Graphic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Graphic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Graphic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea generateLinkField;
    private javax.swing.JButton genereteButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numberFile;
    private javax.swing.JLabel numberFileLabel;
    private javax.swing.JButton showFilesButton;
    private javax.swing.JRadioButton wgetRadio;
    // End of variables declaration//GEN-END:variables
}
